version: '3.8'
services:
  backend:
    build: .
    container_name: university_backend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    command: ["node", "dist/main.js"]
    depends_on:
      - frontend
  frontend:
    build:
      context: ../university_app_frontend
    container_name: university_frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ../university_app_frontend:/app
    command: ["pnpm", "run", "preview", "--", "--host"]
    depends_on: []
